[project]
name = "payment-gateway-api"
version = "0.1.0"
description = "Payment Gateway API test by DjellalAbdou"
authors = [{name =  "DjellalAbdou", email = "ahmed.a.djellal@gmail.com"}]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi (==0.141.1)"
]

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
requests = "^2.34.2"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
